`timescale 1ns/1ps
`define CYCLE 6.0 

module cpu_tb;
    reg clk;
    reg reset;

    // Memory for playback (Match the depth to your binary files)
    reg [4:0]  expected_reg_addr [0:200];
    reg [31:0] expected_reg_data [0:200];
    reg [31:0] expected_sw_addr  [0:200];
    reg [31:0] expected_sw_data  [0:200];
    reg [31:0] expected_lw_addr  [0:200];
    reg [31:0] expected_lw_data  [0:200];
    reg [31:0] instr_mem         [0:500];
    
    integer reg_ptr = 0;
    integer lw_ptr = 0;
    integer sw_ptr = 0;
    // Instantiate your CPU
    // Assuming a simple interface: signals are internal or brought to top
    top_module u_top (
        .clk(clk),
        .reset(reset)
    );

    // 1. Clock Generation
    always #(`CYCLE*0.5) clk = ~clk;

    initial begin
        // Load binary files generated by Python
        $readmemb("instr_data.bin", instr_mem); // You'll need logic to map this to PC
        $readmemb("reg_addr.bin",   expected_reg_addr);
        $readmemb("reg_data.bin",   expected_reg_data);
        $readmemb("sw_addr.bin",   expected_sw_addr);
        $readmemb("sw_data.bin",   expected_sw_data);
        $readmemb("lw_addr.bin",   expected_lw_addr);
        $readmemb("lw_data.bin",   expected_lw_data);
    end
    // 2. State Seeding and File Loading
    initial begin
        clk = 0;
        reset = 1;
        #1 reset = 0;
        #1 reset = 1;    
    end

    // 3. Scoreboard Logic
    // Monitor the retirement (Write-Back) stage
    always @(posedge clk) begin
        if (reset && u_top.u_core.wb_valid) begin
            // Check Register Address
            if (u_top.u_core.wb_reg_addr !== expected_reg_addr[reg_ptr][4:0]) begin
                $display("ERROR: Reg Addr Mismatch at PC %h. Exp: %d, Got: %d", 
                         u_top.u_core.wb_pc, expected_reg_addr[reg_ptr][4:0], u_top.u_core.wb_reg_addr);
                $finish;
            end
            
            // Check Register Data
            if (u_top.u_core.wb_reg_data !== expected_reg_data[reg_ptr]) begin
                $display("ERROR: Reg Data Mismatch at PC %h. Exp: %h, Got: %h", 
                         u_top.u_core.wb_pc, expected_reg_data[reg_ptr], u_top.u_core.wb_reg_data);
                $finish;
            end
            reg_ptr = reg_ptr + 1;
        end

        // 4. Magic Exit Condition
        if (u_top.u_core.pc==32'h100fc0) begin
            $display("SUCCESS: Matrix Multiplication Finished.");
            $finish;
        end
    end

endmodule