`timescale 1ns/1ps
`define CYCLE 8.0 

module cpu_tb;

    localparam END_PC=32'h000100fc;

    // Memory for playback (Match the depth to your binary files)
    reg [4:0]  expected_reg_addr [0:200];
    reg [31:0] expected_reg_data [0:200];
    reg [31:0] expected_sw_addr  [0: 64];
    reg [31:0] expected_sw_data  [0: 64];
    reg [31:0] expected_lw_addr  [0:128];
    reg [31:0] expected_lw_data  [0:128];
    
    integer i;
    integer reg_ptr;
    integer lw_ptr;
    integer sw_ptr;


    reg clk;
    reg rst_n;
    wire mem_read_D;
	wire mem_write_D;
	wire [31:4] mem_addr_D;
	wire [127:0] mem_wdata_D;
	wire [127:0] mem_rdata_D;
	wire mem_ready_D;

	wire mem_read_I;
	wire mem_write_I;
	wire [31:4] mem_addr_I;
	wire [127:0] mem_wdata_I;
	wire [127:0] mem_rdata_I;
	wire mem_ready_I;
	
	wire [31:0]	DCACHE_addr;
	wire [31:0]	DCACHE_wdata;
	wire 		DCACHE_wen;
	
	wire [7:0] error_num;
    // Instantiate your CPU
    // Assuming a simple interface: signals are internal or brought to top

    CHIP#(
    .PC_START(32'h000100b4)
    ) chip0 (
        clk,
		rst_n,
		mem_read_D,
		mem_write_D,
		mem_addr_D,
		mem_wdata_D,
		mem_rdata_D,
		mem_ready_D,
		mem_read_I,
		mem_write_I,
		mem_addr_I,
		mem_wdata_I,
		mem_rdata_I,
		mem_ready_I,
		DCACHE_addr,
		DCACHE_wdata,
		DCACHE_wen
	);
    
    slow_memory#(
        .OFFSET(5047),
        .MEM_NUM(52),
        .MEM_WIDTH(128),
        .LATENCY(15)
    ) slow_memD(
		clk,
		mem_read_D,
		mem_write_D,
		mem_addr_D,
		mem_wdata_D,
		mem_rdata_D,
		mem_ready_D
	);

	slow_memory#(
        .OFFSET(4107),//~4209
        .MEM_NUM(102),
        .MEM_WIDTH(128),
        .LATENCY(15)
    ) slow_memI(
		clk,
		mem_read_I,
		mem_write_I,
		mem_addr_I,
		mem_wdata_I,
		mem_rdata_I,
		mem_ready_I
	);
    
    
    initial begin
        reg_ptr = 0;
        lw_ptr = 0;
        sw_ptr = 0;
        // Load binary files generated by Python
        $readmemb ("instr_final.bin", slow_memI.mem ); // initialize data in IMEM // You'll need logic to map this to PC
        $readmemb("reg_addr.bin",   expected_reg_addr);
        $readmemb("reg_data.bin",   expected_reg_data);
        $readmemb("sw_addr.bin",   expected_sw_addr);
        $readmemb("sw_data.bin",   expected_sw_data);
        $readmemb("lw_addr.bin",   expected_lw_addr);
        $readmemb("lw_data.bin",   expected_lw_data);
        for (i=0;i<52;i=i+1)begin
            slow_memD.mem[i]=32'd0;
        end
    end
    // 1. Clock Generation
    always #(`CYCLE*0.5) clk = ~clk;

    // 2. State Seeding and File Loading
    initial begin
        $dumpfile("dump.vcd");
        $dumpvars;
    end
    initial begin
        
	    
        clk = 0;
        rst_n = 1;
        #1 rst_n = 0;
        #1 rst_n = 1;    
        #(`CYCLE*10000)	 // calculate clock cycles for all operation
		$display("-----------------------------------------------------\n");
		$display("Time out.There is something wrong with your code ...!\n");
	 	$display("------The test result is .....FAIL ------------------\n");
	 	$display("-----------------------------------------------------\n");
	 	$finish;
    end

    always@( negedge clk )	begin
		if(chip0.i_MIPS.u_if_stage.pc_r == END_PC) begin
            $display("reg write target completed: %d",reg_ptr);
			$display("--------------------------- Simulation FINISH !!---------------------------");
			$finish;
		end
	end

    // 3. Scoreboard Logic
    // Monitor the retirement (Write-Back) stage
    
    always @(posedge clk) begin
        if ( chip0.i_MIPS.u_id_stage.MEMWB_ctrl_regw && 
             chip0.i_MIPS.u_if_stage.pc_r >=32'h100e8) begin
            // Check Register Address
            if (chip0.i_MIPS.u_id_stage.MEMWB_regw_addr === expected_reg_addr[reg_ptr] &&
                chip0.i_MIPS.u_id_stage.MEMWB_regw_data === expected_reg_data[reg_ptr]) begin
                    reg_ptr = reg_ptr + 1;
            end
        end
    end
    
endmodule