`timescale 1ns/1ps
`define CYCLE 8.0 

module cpu_tb;
    localparam PC_START= 32'h00010228;   //32'h000100b4;
    localparam PC_VALID= 32'h00000000;   //32'h100e8;
    localparam END_PC=   32'h000103c0;   //32'h000100fc;
    localparam OFFSET_D= 134217681;   //5047
    localparam OFFSET_I= 4124;   //4107

    // Memory for playback (Match the depth to your binary files)
    reg [4:0]  expected_reg_addr [0:200];
    reg [31:0] expected_reg_data [0:200];
    reg [31:0] expected_sw_addr  [0: 64];
    reg [31:0] expected_sw_data  [0: 64];
    reg [31:0] expected_lw_addr  [0:128];
    reg [31:0] expected_lw_data  [0:128];
    
    integer i;
    integer reg_ptr;
    integer lw_ptr;
    integer sw_ptr;


    reg clk;
    reg rst_n;
    wire mem_read_D;
	wire mem_write_D;
	wire [31:4] mem_addr_D;
	wire [127:0] mem_wdata_D;
	wire [127:0] mem_rdata_D;
	wire mem_ready_D;

	wire mem_read_I;
	wire mem_write_I;
	wire [31:4] mem_addr_I;
	wire [127:0] mem_wdata_I;
	wire [127:0] mem_rdata_I;
	wire mem_ready_I;
	
	wire [31:0]	DCACHE_addr;
	wire [31:0]	DCACHE_wdata;
	wire 		DCACHE_wen;
	
	wire [7:0] error_num;
    // Instantiate your CPU
    // Assuming a simple interface: signals are internal or brought to top

    CHIP#(
    .PC_START(PC_START)
    ) chip0 (
        clk,
		rst_n,
		mem_read_D,
		mem_write_D,
		mem_addr_D,
		mem_wdata_D,
		mem_rdata_D,
		mem_ready_D,
		mem_read_I,
		mem_write_I,
		mem_addr_I,
		mem_wdata_I,
		mem_rdata_I,
		mem_ready_I,
		DCACHE_addr,
		DCACHE_wdata,
		DCACHE_wen
	);
    
    slow_memory#(
        .OFFSET(OFFSET_D),
        .MEM_NUM(52),
        .MEM_WIDTH(128),
        .LATENCY(15)
    ) slow_memD(
		clk,
		mem_read_D,
		mem_write_D,
		mem_addr_D,
		mem_wdata_D,
		mem_rdata_D,
		mem_ready_D
	);

	slow_memory#(
        .OFFSET(OFFSET_I),//~4209
        .MEM_NUM(102),
        .MEM_WIDTH(128),
        .LATENCY(15)
    ) slow_memI(
		clk,
		mem_read_I,
		mem_write_I,
		mem_addr_I,
		mem_wdata_I,
		mem_rdata_I,
		mem_ready_I
	);
    //initialize reg state
    initial begin
        // Reset all registers to zero first
        for (i = 0; i < 32; i = i + 1) begin
            chip0.i_MIPS.u_id_stage.register_r[i] = 32'h00000000;
        end

       // 2. Core Pointer Initialization
        chip0.i_MIPS.u_id_stage.register_r[1]  = 32'h0001015c; // ra: Return Address
        chip0.i_MIPS.u_id_stage.register_r[2]  = 32'h7ffffda0; // sp: Stack Pointer (New value)
        chip0.i_MIPS.u_id_stage.register_r[3]  = 32'h00013a78; // gp: Global Pointer

        // 3. Temporary Registers
        chip0.i_MIPS.u_id_stage.register_r[5]  = 32'h00010c84; // t0
        chip0.i_MIPS.u_id_stage.register_r[6]  = 32'h0000000f; // t1
        // t2 is 0x0 according to your Spike log

        // 4. Function Arguments / a-registers
        chip0.i_MIPS.u_id_stage.register_r[10] = 32'h00000001; // a0
        chip0.i_MIPS.u_id_stage.register_r[11] = 32'h7ffffda4; // a1 (Pointing to stack)
        chip0.i_MIPS.u_id_stage.register_r[12] = 32'h7ffffdac; // a2 (Pointing to stack)
        chip0.i_MIPS.u_id_stage.register_r[14] = 32'h00000001; // a4

    end
    
    initial begin
        reg_ptr = 0;
        lw_ptr = 0;
        sw_ptr = 0;
        // Load binary files generated by Python
        $readmemb ("instr_final.bin", slow_memI.mem ); // initialize data in IMEM // You'll need logic to map this to PC
        $readmemb("reg_addr.bin",   expected_reg_addr);
        $readmemb("reg_data.bin",   expected_reg_data);
        $readmemb("sw_addr.bin",   expected_sw_addr);
        $readmemb("sw_data.bin",   expected_sw_data);
        $readmemb("lw_addr.bin",   expected_lw_addr);
        $readmemb("lw_data.bin",   expected_lw_data);
        for (i=0;i<52;i=i+1)begin
            slow_memD.mem[i]=32'd0;
        end
    end
    // 1. Clock Generation
    always #(`CYCLE*0.5) clk = ~clk;

    // 2. State Seeding and File Loading
    initial begin
        $dumpfile("dump.vcd");
        $dumpvars;
    end
    initial begin
        
	    
        clk = 0;
        rst_n = 1;
        #1 rst_n = 0;
        #1 rst_n = 1;    
        #(`CYCLE*10000)	 // calculate clock cycles for all operation
		$display("-----------------------------------------------------\n");
		$display("Time out.There is something wrong with your code ...!\n");
	 	$display("------The test result is .....FAIL ------------------\n");
	 	$display("-----------------------------------------------------\n");
	 	$finish;
    end

    always@( negedge clk )	begin
		if(chip0.i_MIPS.u_if_stage.pc_r == END_PC) begin
            $display("reg write target completed: %d",reg_ptr);
            $display("LW target completed: %d",lw_ptr);
            $display("SW target completed: %d",sw_ptr);
			$display("--------------------------- Simulation FINISH !!---------------------------");
			$finish;
		end
	end

    // 3. Scoreboard Logic
    // Monitor the retirement (Write-Back) stage
    wire [32:0] reg_target=expected_reg_data[reg_ptr];
    wire [32:0] reg_target_addr=expected_reg_addr[reg_ptr];

    always @(posedge clk) begin
        if ( chip0.i_MIPS.u_id_stage.MEMWB_ctrl_regw && 
             chip0.i_MIPS.u_if_stage.pc_r >=PC_VALID) begin
            // Check Register Address
            if (chip0.i_MIPS.u_id_stage.MEMWB_regw_addr === expected_reg_addr[reg_ptr] &&
                chip0.i_MIPS.u_id_stage.MEMWB_regw_data === expected_reg_data[reg_ptr]) begin
                    //$display("reg write complete: %h",expected_reg_data[reg_ptr]);
                    reg_ptr = reg_ptr + 1;
            end
        end
    end
    always @(posedge clk) begin //lw check
        if ( chip0.i_MIPS.u_mem_stage.DCACHE_ren && 
             chip0.i_MIPS.u_if_stage.pc_r >=PC_VALID) begin
            // Check Register Address
            if (chip0.i_MIPS.u_mem_stage.DCACHE_addr  === expected_lw_addr[lw_ptr] &&
                chip0.i_MIPS.u_mem_stage.DCACHE_rdata === expected_lw_data[lw_ptr]) begin
                    //$display("lw complete: %h",expected_lw_data[lw_ptr]);
                    lw_ptr = lw_ptr + 1;
            end
        end
    end
    always @(posedge clk) begin //sw check
        if ( chip0.i_MIPS.u_mem_stage.DCACHE_wen && 
             chip0.i_MIPS.u_if_stage.pc_r >=PC_VALID) begin
            // Check Register Address
            if (chip0.i_MIPS.u_mem_stage.DCACHE_addr  === expected_sw_addr[sw_ptr] &&
                chip0.i_MIPS.u_mem_stage.DCACHE_wdata === expected_sw_data[sw_ptr]) begin
                    //$display("sw complete: %h",expected_sw_data[sw_ptr]);
                    sw_ptr = sw_ptr + 1;
            end
        end
    end
endmodule